# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `bundle install` to run rake tasks'
end

APP_RAKEFILE = File.expand_path('../test/dummy/Rakefile', __dir__)
load 'rails/tasks/engine.rake' if File.exist?(APP_RAKEFILE)
load 'rails/tasks/rails.rake'
load 'rails/tasks/testing.rake'
